### ISSUE TITLE
React v15

### ISSUE THREAD

**Issue by kachkaev** [qubitdigital/d3-react-sparkline#3]
Could you please update react version in peer deps? `npm install` does not work for react v15.
Example commit: https://github.com/STRML/react-resizable/commit/9a5a3e514deac1ec4ffa2074f8dd8cb716f26008

**Comment by Olical** [comment]
On it. I like the optional 0.14 / 15, I'll use that.

**Comment by Olical** [comment]
Going to use `"react": "*"` because I'm not doing anything fancy and this sort of thing will be an issue for people in the future. I'm already doing the same with D3.
